### ISSUE TITLE
Merge error: conflicting capitalizations

### ISSUE THREAD

**Issue by jaredcnance** [davidchambers/Base64.js#24]
Copied from: https://github.com/simplabs/ember-simple-auth/issues/766
I'm running OS X El Capitan 10.11.1
It seems to be related to the base64 install
```
Future versions of Ember CLI will not support v5.0.0. Please update to Node 0.12 or io.js.
version: 1.13.8
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
Merge error: conflicting capitalizations:
base64 in /Users/jarednance/Code/ember-simple-auth/tmp/broccoli_merge_trees-input_base_path-TFvTJRgu.tmp/8
Base64 in /Users/jarednance/Code/ember-simple-auth/tmp/broccoli_merge_trees-input_base_path-TFvTJRgu.tmp/34
Remove one of the files and re-add it with matching capitalization.
We are strict about this to avoid divergent behavior between case-insensitive Mac/Windows and case-sensitive Linux.
Error: Merge error: conflicting capitalizations:
base64 in /Users/jarednance/Code/ember-simple-auth/tmp/broccoli_merge_trees-input_base_path-TFvTJRgu.tmp/8
Base64 in /Users/jarednance/Code/ember-simple-auth/tmp/broccoli_merge_trees-input_base_path-TFvTJRgu.tmp/34
Remove one of the files and re-add it with matching capitalization.
We are strict about this to avoid divergent behavior between case-insensitive Mac/Windows and case-sensitive Linux.
    at mergeRelativePath (/Users/jarednance/Code/ember-simple-auth/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:59:19)
    at BroccoliMergeTrees.build (/Users/jarednance/Code/ember-simple-auth/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:26:3)
    at /Users/jarednance/Code/ember-simple-auth/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/jarednance/Code/ember-simple-auth/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/jarednance/Code/ember-simple-auth/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/jarednance/Code/ember-simple-auth/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/Users/jarednance/Code/ember-simple-auth/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
```

**Comment by davidchambers** [comment]
Perhaps the problem is that both [Base64][1] and [base64][2] exist in the registry.


[1]: https://www.npmjs.com/package/Base64
[2]: https://www.npmjs.com/package/base64

**Comment by michaelficarra** [comment]
And that you're using a case-insensitive filesystem.

**Comment by H3Chief** [comment]
Did bower prevent you from publishing the module with the capitalization? Just curious why you would publish to npm with `Base64`, and then publish to bower using `base64`?

**Comment by davidchambers** [comment]
@H3Chief, I don't recall the sequence of events which led to the repository, the npm package, and the Bower package having three different names! Were I to go back in time I would make these consistent.
